LBPUnion/ProjectLighthouse

ProjectLighthouse.Tests/DatabaseFact.cs, ProjectLighthouse.Tests/LighthouseTest.cs, ProjectLighthouse.Tests/ProjectLighthouse.Tests.csproj, ProjectLighthouse.Tests/ProjectLighthouse.Tests.csproj.DotSettings, ProjectLighthouse.Tests/Tests/AuthenticationTest.cs, ProjectLighthouse.Tests/Tests/AuthenticationTests.cs, ProjectLighthouse.Tests/Tests/SerializerTests.cs, ProjectLighthouse.sln, ProjectLighthouse/Controllers/LoginController.cs, ProjectLighthouse/Controllers/MessageController.cs, ProjectLighthouse/Database.cs, ProjectLighthouse/Helpers/BinaryHelper.cs, ProjectLighthouse/Types/LoginResult.cs, ProjectLighthouse/Types/ServerSettings.cs
This branch adds unit tests, which can be very useful for a project like this. I figured it would be good to get this done early, so here we are.
I'm making this merge request because I've never done unit testing in C# before and just wanted to make sure this was a decent way of doing it.
I've already found a bug (see 4bce25e) with this, so it'll definitely be useful in the long run
=> Unit Testing

ProjectLighthouse/Controllers/PublishController.cs, ProjectLighthouse/Types/ServerSettings.cs, ProjectLighthouse/Types/Slot.cs
=> Level uploading

ProjectLighthouse.Tests/Tests/AuthenticationTests.cs, ProjectLighthouse.sln.DotSettings, ProjectLighthouse/Controllers/ScoreController.cs, ProjectLighthouse/Helpers/Extensions/StringExtensions.cs, ProjectLighthouse/Logging/LighthouseFileLogger.cs, ProjectLighthouse/ProjectLighthouse.csproj, ProjectLighthouse/Serialization/LbpSerializer.cs, ProjectLighthouse/Types/Score.cs
Lots going on here, so I'll break down the decisions I made/things I've done:
- Added another definition of TaggedStringElement which allows providing a dictionary of key/value pairs, for cases were an XML tag has multiple attributes. You can see how I use it when sending the `<scores />` tag to the game.
- Fixed a bug I noticed when submitting scores that would submit a new score by the same person each time a level is completed, rather than update their best highscore. I'm aware that there's probably something database related that could be done to enforce a unique constraint on the `PlayerIdCollection` but for now I just did the checking all in code.
- Added endpoint for `topscores`
Most of the `TopScores` code should be straight forward with the comments. I did my best to try to …
=> Add support for grabbing Top Scores

ProjectLighthouse/Pages/SlotsPage.cshtml, ProjectLighthouse/Pages/SlotsPage.cshtml.cs
=> Improve pagination of the level listing

README.md
Adds a tutorial to play LBP1 on RPCS3
=> [skip ci] Update README.md with a tutorial on patching LBP1 for RPCS3

README.md
im so sorry I promise this will be the last pull request
=> [skip ci] Fix the formatting

ProjectLighthouse/Controllers/ResourcesController.cs, ProjectLighthouse/Helpers/WebhookHelper.cs, ProjectLighthouse/Pages/LoginForm.cshtml, ProjectLighthouse/Pages/PhotosPage.cshtml, ProjectLighthouse/Pages/PhotosPage.cshtml.cs, ProjectLighthouse/Pages/RegisterForm.cshtml, ProjectLighthouse/Pages/SlotsPage.cshtml, ProjectLighthouse/Pages/SlotsPage.cshtml.cs, ProjectLighthouse/Pages/UsersPage.cshtml, ProjectLighthouse/Pages/UsersPage.cshtml.cs, ProjectLighthouse/Program.cs
This PR adds basic search functionality to users, photos, and levels as well as fixes some bugs like:
* when there are zero photos/slots/users the invalid page redirect will cause an error when trying to clamp because the page number will be -1
* Even if webhook integration is disabled, the WebhookHelper will still try to initialize a WebhookClient which will cause an error if there is no URL specified.
* If you have never run the instance before, the png folder won't get created and as a result, all related features fail to work
* Fixed a visual issue with the login and register page where after you hit submit the password field gets updated to the hashed version which causes the user to see the login field filled with characters. My fix still hashes the password and doesn't send the …
=> Added basic search functionality and fixed some bugs

ProjectLighthouse/Controllers/GameApi/Slots/ReviewController.cs, ProjectLighthouse/Types/Levels/Slot.cs
Review button go brr
Closes #107
=> Fix review button not showing up

ProjectLighthouse/Helpers/InfluxHelper.cs, ProjectLighthouse/Helpers/StatisticsHelper.cs
=> Log recent matches for individual games to InfluxDB

ProjectLighthouse/Controllers/GameApi/Slots/ReviewController.cs
=> Fix reviews not being excluded by level id

ProjectLighthouse/Pages/Partials/CommentsPartial.cshtml, ProjectLighthouse/Pages/SlotPage.cshtml, ProjectLighthouse/Pages/SlotPage.cshtml.cs, ProjectLighthouse/StaticFiles/css/styles.css
Here's what it looks like on a level with mixed reviews:
Vita's review icons are a little smaller for some strange reason, but they still look alright:
*Closes #234*
=> Add reviews to slot page

ProjectLighthouse/Controllers/GameApi/Slots/SlotsController.cs
Someone kinda broke production but this should fix it.
=> Fix include slot location and creator arg

ProjectLighthouse/Pages/SlotsPage.cshtml.cs
My local branch was chalked after the yml update so I just made another branch
=> Fix total level count

ProjectLighthouse.Servers.GameServer/Controllers/Slots/PublishController.cs
This makes the title and description limits for levels more accurate to what they actually are on a console.
=> Fix level text limits

ProjectLighthouse.Servers.Website/Pages/PhotosPage.cshtml, ProjectLighthouse.Servers.Website/Pages/ReportsPage.cshtml, ProjectLighthouse.Servers.Website/Pages/SlotsPage.cshtml, ProjectLighthouse.Servers.Website/Pages/UsersPage.cshtml
=> Disabled autocomplete on search boxes

ProjectLighthouse.Servers.GameServer/Controllers/Resources/ResourcesController.cs
Hm I wonder who could have possible made this mistake
=> Fix duplicate resource uploading

ProjectLighthouse.Servers.GameServer/Controllers/Slots/ListController.cs
According to EntityFramework you have to call .Include before .Select otherwise the query fails.
=> Fix heart and queue lists

ProjectLighthouse.Servers.GameServer/Controllers/MessageController.cs, ProjectLighthouse/Configuration/ServerConfiguration.cs
Reopening #387 without EULA changes
Fixes #376
=> Don't send new line if announce text is blank

ProjectLighthouse/PlayerData/Reviews/Review.cs
Game doesn't like `User`, only `user`
=> Fix reviews not showing up

ProjectLighthouse.Servers.GameServer/Controllers/Slots/SlotsController.cs, ProjectLighthouse/Levels/Slot.cs
I found some packet captures for /slots/developer, idk how the game actually uses this but I thought I may as well implement it.
=> Implement story mode player counts endpoint

ProjectLighthouse.Servers.GameServer/Controllers/UserController.cs, ProjectLighthouse/PlayerData/Profiles/UserUpdate.cs, ProjectLighthouse/PlayerData/Profiles/UserUpdateSlot.cs
This PR implements support for moving levels when you are in decorate mode on your earth.
=> Add support for moving levels with decoration tool

ProjectLighthouse.Servers.GameServer/Controllers/ClientConfigurationController.cs, ProjectLighthouse.Servers.GameServer/Controllers/DeveloperController.cs, ProjectLighthouse.Servers.GameServer/Controllers/Matching/MatchController.cs, ProjectLighthouse.Servers.GameServer/Startup/GameServerStartup.cs
Hopefully, this prevents the game from crashing so often by implementing more endpoints that were on the original servers.
=> Reduce crashing on LBP3 (Hopefully)

ProjectLighthouse.Servers.GameServer/Controllers/ClientConfigurationController.cs, ProjectLighthouse.Servers.GameServer/Controllers/LoginController.cs, ProjectLighthouse.Servers.GameServer/Controllers/Slots/ScoreController.cs, ProjectLighthouse.Servers.GameServer/Middlewares/DigestMiddleware.cs, ProjectLighthouse/Configuration/ServerConfiguration.cs, ProjectLighthouse/Extensions/RequestExtensions.cs, ProjectLighthouse/PlayerData/LoginResult.cs
This PR opens the door for previously thought impossible LBP3 features like Challenges and Dive In
- Adds titleStorageURL to the loginResult response
- Fixes friend scores
- Adds an GameApiExternalUrl to the config so the game knows where to request user resources and other network resources
=> Add unimplemented LBP3 login option

ProjectLighthouse.Servers.Website/Pages/SlotSettingsPage.cshtml
=> Add Adventure icon for slot settings 

CONTRIBUTING.md
=> Update CONTRIBUTING.md 2: Electric Boogaloo

.gitignore, ProjectLighthouse.Servers.GameServer/Controllers/UserController.cs, ProjectLighthouse/Migrations/20221117165700_AddCrossControlPlanet.cs, ProjectLighthouse/PlayerData/Profiles/User.cs, ProjectLighthouse/PlayerData/Profiles/UserUpdate.cs
This fixes the problem where you can't apply custom planets with LBP2 Cross Controller active, happy creating!
=> Add support for Cross Controller Planets

ProjectLighthouse.Servers.GameServer/Controllers/Slots/CollectionController.cs, ProjectLighthouse.Servers.GameServer/Controllers/StatisticsController.cs, ProjectLighthouse/Levels/Categories/HeartedCategory.cs
=> Total level count shows compatible levels instead of levels uploaded all throughout lighthouse. 

ProjectLighthouse.Servers.GameServer/Controllers/Slots/ScoreController.cs
=> Fix ScoreController making scores of other players

ProjectLighthouse/Levels/Categories/CategoryHelper.cs, ProjectLighthouse/Levels/Categories/HighestRatedCategory.cs, ProjectLighthouse/Levels/Categories/MostHeartedCategory.cs, ProjectLighthouse/Levels/Categories/MostPlayedCategory.cs
Adds Most Hearted, Most Played, and Highest Rated category to LBP3
=> Added three new categories to LBP3

ProjectLighthouse/Helpers/GameVersionHelper.cs
Added a Hub ID and 4 Move IDs (Sackboy’s Prehistoric Moves). And removed a duplicated GameID
=> Added some more GameIDs

ProjectLighthouse.Servers.GameServer/Controllers/Slots/SlotsController.cs, ProjectLighthouse.Servers.Website/ProjectLighthouse.Servers.Website.csproj, ProjectLighthouse.Tests.GameApiTests/ProjectLighthouse.Tests.GameApiTests.csproj, ProjectLighthouse.Tests.WebsiteTests/ProjectLighthouse.Tests.WebsiteTests.csproj, ProjectLighthouse.Tests/ProjectLighthouse.Tests.csproj, ProjectLighthouse/PlayerData/Profiles/User.cs, ProjectLighthouse/ProjectLighthouse.csproj
Fixes a bug with yourReview where the slot type wouldn't be included
Fixes a bug with crossControllerPlanet where it would be included even if it was null or empty
=> Fix bugs and bump dependencies

ProjectLighthouse/Match/Rooms/Room.cs
Found a try/catch that was being used as a cursed if statement so I fixed it <3
=> Remove a jvydenism

.gitpod.yml, ProjectLighthouse.Servers.Website/Pages/Errors/NotFoundPage.cshtml, ProjectLighthouse.Servers.Website/Pages/Partials/CommentsPartial.cshtml, ProjectLighthouse.Servers.Website/Pages/UserPage.cshtml, ProjectLighthouse.Servers.Website/Pages/UserPage.cshtml.cs
... so Mike stops complaining about the neglected mod menu :trollface:
=> Website QOL Changes

ProjectLighthouse.Servers.Website/Pages/Partials/CommentsPartial.cshtml
Hotfix for comments not actually being disabled if a user is banned (whoops)
=> Fix comments not being disabled if banned

ProjectLighthouse.Servers.Website/Pages/Errors/NotFoundPage.cshtml, ProjectLighthouse.Servers.Website/Pages/Partials/CommentsPartial.cshtml, ProjectLighthouse.Servers.Website/Pages/UserPage.cshtml
Attempt 2 at some website quality of life changes. Starting with visual fixes/changes, will need to go back and add a few more things such as Quick Dismiss Case button/other back-end edits at some point.
=> Website visual QOL changes

ProjectLighthouse/Middlewares/RateLimitMiddleware.cs
Fixes the built-in rate limiter of Lighthouse to use regex matching to count the number of requests the user has made for a specific zone. The old implementation would just count the number of requests that matched the URL exactly which meant for a rate limit zone over /user/* someone could exceed the rate limit at /user/15 and then exceed the rate limit again at /user/16. This is now prevented because all requests are properly counted.
Also adds a page for when you reach the rate limit rather than just letting the browser give a default 429 error.
=> Make rate limiter match zone rather than directly comparing url

ProjectLighthouse.Servers.API/Controllers/UserEndpoints.cs
This adds an API endpoint for searching for users based on a query
I have two things in mind for this
- A more responsive user search in the future for the website
- User searching/verification in a newer version of CrashHelper
=> User Search API

ProjectLighthouse.Servers.Website/Pages/Partials/Links/UserLinkPartial.cshtml, ProjectLighthouse.Servers.Website/Pages/Partials/UserCardPartial.cshtml, ProjectLighthouse/StaticFiles/css/styles.css, ProjectLighthouse/Types/Users/PermissionLevel.cs
Add moderator/admin badges to UserCardPartial. Extension of #670.
=> Add admin/mod badges on UserCardPartial

ProjectLighthouse.Servers.GameServer/Controllers/MessageController.cs
I thought I already made this change since I implemented the `SendVerificationEmail` method but I guess I forgot.
=> Make in-game email system not lock after one attempt

ProjectLighthouse.Servers.Website/Pages/SlotPage.cshtml.cs
this GROUNDBREAKING pr potentially fixes an issue where the scores are sorted wrong
i have no idea if it works and i hope you all enjoy this because i dont have the environment to test it atm.
@sudokoko
=> Potentially fix score sorting issue

CONTRIBUTING.md
More minor copyediting that i forgot to do until more than 6 months after i did my last pr lol
=> Update CONTRIBUTING.md 3: Minor grammar and capitalization issues

ProjectLighthouse.Servers.Website/Extensions/FormattingExtensions.cs, ProjectLighthouse.Servers.Website/Pages/Partials/Links/UserLinkPartial.cshtml, ProjectLighthouse.Servers.Website/Pages/Partials/SlotCardPartial.cshtml, ProjectLighthouse.Servers.Website/Pages/Partials/UserCardPartial.cshtml, ProjectLighthouse/Types/Entities/Level/SlotEntity.cs, ProjectLighthouse/Types/Users/PermissionLevel.cs
Display a lock icon next to an `InitiallyLocked` level
=> Display a lock icon next to locked levels

ProjectLighthouse/Files/FileHelper.cs, ProjectLighthouse/Files/LbpFileParser.cs, ProjectLighthouse/Types/Resources/LbpFileType.cs
Fixes publishing LBP3 levels that use dynamic thermometers.
=> Allow streaming chunk filetype in mod filter

ProjectLighthouse.Localization/BaseLayout.resx, ProjectLighthouse.Localization/StringLists/BaseLayoutStrings.cs, ProjectLighthouse.Servers.Website/Pages/Layouts/BaseLayout.cshtml
Only display "Login" as opposed to "Login / Register" when `ServerConfiguration.Instance.Authentication.RegistrationEnabled` is false
=> String fix with login/register button

ProjectLighthouse.Servers.API/Responses/ApiUser.cs
Adds the permission level key into the response of `/api/v1/user`.
=> Add moderation/permission info to /api/v1/user

ProjectLighthouse.Localization/Error.resx, ProjectLighthouse.Localization/StringLists/ErrorStrings.cs, ProjectLighthouse.Servers.Website/Pages/Moderation/NewCasePage.cshtml, ProjectLighthouse.Servers.Website/Pages/Moderation/NewCasePage.cshtml.cs
=> Disallow moderators/administrators from issuing cases against each other

ProjectLighthouse.Servers.GameServer/Controllers/Slots/SlotsController.cs, ProjectLighthouse.Servers.GameServer/Extensions/ControllerExtensions.cs, ProjectLighthouse.Tests.GameApiTests/Unit/Controllers/ControllerExtensionTests.cs, ProjectLighthouse.Tests.GameApiTests/Unit/Controllers/SlotControllerTests.cs, ProjectLighthouse.Tests/Unit/FilterTests.cs, ProjectLighthouse/Filter/Filters/AdventureFilter.cs, ProjectLighthouse/Filter/Filters/CreatorFilter.cs, ProjectLighthouse/Filter/Filters/CrossControlFilter.cs, ProjectLighthouse/Filter/Filters/ExcludeAdventureFilter.cs, ProjectLighthouse/Filter/Filters/ExcludeCrossControlFilter.cs, ProjectLighthouse/Filter/Filters/ExcludeLBP1OnlyFilter.cs, ProjectLighthouse/Filter/Filters/GameVersionFilter.cs, ProjectLighthouse/Filter/Filters/HiddenSlotFilter.cs, ProjectLighthouse/Filter/Filters/MovePackFilter.cs, ProjectLighthouse/Filter/Filters/ResultTypeFilter.cs, ProjectLighthouse/Filter/Filters/SlotTypeFilter.cs, ProjectLighthouse/Filter/Filters/SubLevelFilter.cs, ProjectLighthouse/Filter/Filters/TeamPickFilter.cs, ProjectLighthouse/Helpers/LastContactHelper.cs
Also sort author levels by oldest levels first rather than newest levels first.
=> Simplify filters and make cross control slots not show by default

ProjectLighthouse.Servers.API/Controllers/UserEndpoints.cs
Reverts LBPUnion/ProjectLighthouse#789
=> Revert "Add online users endpoint to user API"

ProjectLighthouse/Configuration/CensorConfiguration.cs, ProjectLighthouse/Helpers/CensorHelper.cs
This PR makes several optimizations to the censor filtering system.
* Adds proper logging of censored messages
* Prevents garbage collection & memory problems with larger censored strings
* Dead code removal
=> Optimize censor filter system

ProjectLighthouse.Servers.Website/Pages/Login/BannedUserPage.cshtml, ProjectLighthouse.Servers.Website/Pages/Login/BannedUserPage.cshtml.cs
=> Handle edge case bug in banned page

ProjectLighthouse.Servers.Website/Pages/Admin/AdminPanelPage.cshtml
=> Do not autocomplete admin command form values

ProjectLighthouse.Servers.Website/Extensions/FormattingExtensions.cs, ProjectLighthouse.Servers.Website/Pages/Moderation/NewCasePage.cshtml, ProjectLighthouse.Servers.Website/Pages/Moderation/NewCasePage.cshtml.cs
Pretty self explanatory PR - redesigns the case creation page and allows moderators to view previous case history for the affected user when creating a case.
=> Redesign case creation page

ProjectLighthouse.Servers.API/Responses/RpcResponse.cs, ProjectLighthouse/Configuration/ConfigurationCategories/RichPresenceConfiguration.cs, ProjectLighthouse/Configuration/ServerConfiguration.cs
=> Add UseApplicationAssets option to RPC API and configuration

ProjectLighthouse.Tests/Unit/ModerationTests.cs, ProjectLighthouse/Administration/Maintenance/RepeatingTasks/DismissExpiredCasesTask.cs
=> Implement dismiss expired cases repeating task

ProjectLighthouse.Servers.Website/Pages/LandingPage.cshtml.cs
=> Do not show mod-hidden levels on landing page

ProjectLighthouse.Servers.Website/Controllers/SlotPageController.cs, ProjectLighthouse.Servers.Website/Controllers/UserPageController.cs, ProjectLighthouse.Servers.Website/Extensions/SlugExtensions.cs
Prevents slugs from starting or ending with a dash
=> Fix extra whitespace in slot slugs

ProjectLighthouse.Servers.Website/Controllers/Moderator/ModerationRemovalController.cs
Extends #932. Adds notifications for photo, score, comment, and review deletions.
=> Add missing moderation notification calls
