LBPUnion/ProjectLighthouse

.gitignore
.idea/.idea.ProjectLighthouse/.idea/.name
ProjectLighthouse/Controllers/UserController.cs
ProjectLighthouse/Types/Profiles/Pins.cs

Adds support for setting profile pins.
- Tested in LBP2, RPCS3 environment
- Added a new class under Profile in Types for "Pins", because I needed a class in order to deserialize the JSON request body being posted. Hopefully this is the appropriate place to put it.
- If there is a better way to grab the profile_pins key from the `update_my_pins` request without the Pins class, or the class needs more (like the `Serialize` method or xml attributes seen in other "Types"), please let me know. I'm familiarizing myself with C# so I picked a relatively simple task to undertake.
- I'm not sure if the progress and awards fields are used for online play because the `profile_pins` are what's being set in the actual profile. No database changes are needed for my additions because the joined …

Profile pins

---

ProjectLighthouse/Controllers/ReviewController.cs
ProjectLighthouse/Controllers/SlotsController.cs
ProjectLighthouse/Database.cs
ProjectLighthouse/Migrations/20211108212022_BooYayRateLevels.Designer.cs
ProjectLighthouse/Migrations/20211108212022_BooYayRateLevels.cs
ProjectLighthouse/Types/Levels/RatedLevel.cs
ProjectLighthouse/Types/Levels/Slot.cs

Self explanatory, lets a user Yay and Boo levels, as well as send a 5 star rating of a level in LBP1. 
A user that has played a level in both LBP1 and LBP2+ can simultaneously yay/boo a level and have a numeric LBP1 rating associated to them.

Add support for level ratings

---

ProjectLighthouse/Controllers/LoginController.cs
ProjectLighthouse/Controllers/MessageController.cs
ProjectLighthouse/Controllers/Website/ExternalAuth/AutoApprovalController.cs
ProjectLighthouse/Database.cs
ProjectLighthouse/Migrations/20211213195540_AddUserApprovedIpAddresses.cs
ProjectLighthouse/Migrations/20211214005427_AddUsedBoolToGameToken.cs
ProjectLighthouse/Migrations/DatabaseModelSnapshot.cs
ProjectLighthouse/Pages/ExternalAuth/AuthenticationPage.cshtml
ProjectLighthouse/Pages/ExternalAuth/AuthenticationPage.cshtml.cs
ProjectLighthouse/Pages/ExternalAuth/ManageUserApprovedIpAddressesPage.cshtml
ProjectLighthouse/Pages/ExternalAuth/ManageUserApprovedIpAddressesPage.cshtml.cs
ProjectLighthouse/Pages/LandingPage.cshtml
ProjectLighthouse/Pages/LandingPage.cshtml.cs
ProjectLighthouse/Types/GameToken.cs
ProjectLighthouse/Types/Settings/ServerSettings.cs
ProjectLighthouse/Types/UserApprovedIpAddress.cs

This new method no longer lets the user in at all (returns 403 on POST /login) without an approved token. The bad thing about this change is that users may be confused when they see the 403 error screen, but it does solve the problem of the client spamming the server with login attempts.
This also adds a system to allow users to "approve" an IP automatically. Once an IP is approved, they will be able to log into the game with no interaction on the website. They can, of course, revoke the IP from being automatically signed in.
I also touched up the authentication page. Here's how it looks:
I added a new page to manage the whitelisted IPs a user has:
In my testing, the game will still send some spam sometimes (especially after rejecting EULA after logging in) but it will only send 3 …

New authentication system

---

ProjectLighthouse/Pages/Layouts/BaseLayout.cshtml
ProjectLighthouse/Pages/Partials/PhotoPartial.cshtml
ProjectLighthouse/StaticFiles/css/styles.css
ProjectLighthouse/Types/PhotoSubject.cs

This is a feature proposal that could possibly close #91 if approved.
I have implemented a simple JS+HTML Canvas username label+boundary renderer to allow anyone to view the location of photo subjects within a photo, through the main website.
[demo gif](https://media.discordapp.net/attachments/915460867506712637/921616288005120100/Peek_2021-12-17_23-02.gif?width=1067&height=686)
Subject bounds are hidden by default, requiring the user to hover over the subject list to view them. Furthermore, labels will move to stay within the frame if they were to render outside the canvas.
Here is a quick screenshot showing off the colour (multiple players) and label shifting functionality.
- This feature works site-wide, as long as the photo is rendered as a `PhotoPartial`. Labels and their text will …

(Website) View location of photo subjects in photo

---

ProjectLighthouse/Helpers/GameVersionHelper.cs

Added missing Title IDs, these fixes LBP 2 from only showing LBP 1 levels, and reporting as LBP 1 on the server. And fixes LBP 3 from crashing.

Added missing LBP 1, 2 and 3 title ids

---

ProjectLighthouse/Helpers/GameVersionHelper.cs

Added a whole bunch more of Title IDs removed duplicates, fixed formatting, and grouped Retail by itself and Debug, Beta and Demo under a comment. Also grouped PS4 and PS3 versions of LBP 3 by itself

Update GameVersionHelper.cs Bunch more Title IDs and seperated Retail from Debug, Beta and Demo builds

---

ProjectLighthouse/Controllers/GameApi/Slots/SlotsController.cs
ProjectLighthouse/Types/User.cs

Including yourReview was already implemented but somebody forgot to actually fetch the user's potential review in SlotController
This now makes the game recognize that it has already posted a review and replaces the review button with your review at the top of the list
Before:
After:

Send yourReview with slot request

---

ProjectLighthouse.Tests.GameApiTests/AuthenticationTests.cs

This fix was in my last PR but it got yeeted. Currently, the slot upload test and the CanUseToken test cause problems for each other since they both use slot id 1. By using a different slot id that is never valid it prevents the enterLevel controller from passing the existence check and trying to save changes.

Fix race conditoon in tests

---

ProjectLighthouse/Controllers/GameApi/Resources/ResourcesController.cs
ProjectLighthouse/Controllers/GameApi/UserController.cs
ProjectLighthouse/Database.cs
ProjectLighthouse/Pages/UserPage.cshtml
ProjectLighthouse/Types/UserUpdate.cs

I don't know if the other games behave like this but in LBP2 when your biography is empty it shows "[name] hasn't introduced themselves yet" so there is no need for us to manually set it upon creation. This can also be seen as a small quality of life change because right now when you create a new profile you have to manually delete the starting biography text instead of it just being empty.
The resource controller returning 409 instead of 422 when it encounters an unsafe file should also fix #168 but I need someone to test because I am unable to replicate the issue.

Clean up updateUser and some small changes

---

ProjectLighthouse/Migrations/20220402212909_AddAdminGrantedSlotsToUser.cs
ProjectLighthouse/Migrations/DatabaseModelSnapshot.cs
ProjectLighthouse/Pages/Admin/AdminSetGrantedSlotsPage.cshtml
ProjectLighthouse/Pages/Admin/AdminSetGrantedSlotsPage.cshtml.cs
ProjectLighthouse/Pages/Partials/AdminSetGrantedSlotsFormPartial.cshtml
ProjectLighthouse/Pages/UserPage.cshtml
ProjectLighthouse/Types/User.cs

This moves the ban user button to a new Admin Options panel at the bottom of a user page:
The value you set will be applied in addition to the instance's default slot quota, 
So, for example, if the server's slot quota was 50 and you granted 14 additional slots, the total slot quota for that user would be 64.
*Closes #232*

Add ability to grant a user additional slots

---

ProjectLighthouse.Tests.WebsiteTests/ProjectLighthouse.Tests.WebsiteTests.csproj
ProjectLighthouse/Controllers/Website/Admin/AdminReportController.cs
ProjectLighthouse/Pages/ReportsPage.cshtml

First and foremost, I made some improvements to the actual reports themselves.
I added some spacing to different areas of the information, moved the "hover here to view area" text to be the actual image, and increased the size of the buttons a tiny bit.
I also fixed the bug where the canvas would not display. The bug was the height was being set to 0 for some reason.
Lastly, I added the ability to "dismiss" a report instead of having the only available option be going hail mary and deleting all related assets. This simply removes the report from the database, nothing special.

Several improvements to Grief Reports

---

README.md

The hope is that we can link to this section of the README whenever someone tries to ask for support for running an unofficial Project Lighthouse instance.
I also copypasted most of the legalties from the initial Lighthouse article and added it as a new section.

Add some disclaimers to the README

---

ProjectLighthouse.Tests.GameApiTests/UploadTests.cs
ProjectLighthouse.Tests/LighthouseServerTest.cs
ProjectLighthouse/Controllers/GameApi/Resources/ResourcesController.cs
ProjectLighthouse/Controllers/GameApi/Slots/PublishController.cs
ProjectLighthouse/Pages/Partials/CommentsPartial.cshtml
ProjectLighthouse/Pages/Partials/SlotCardPartial.cshtml
ProjectLighthouse/Pages/SlotPage.cshtml

* Reviews are no longer shown if they are deleted (closes #273)
* Reviews now show the missingIconHash if their hash is empty
* Slot version is preserved when republishing instead of defaulting to LBP1 (closes #274)
* Added the `/upload/[hash]/unattributed` endpoint (closes #269)
* Resource endpoints `/r`, `/upload`, `/filterResources` and `/showNotUploaded` now require authentication
* Website now displays play count as the number of unique plays (closes #192)
I also added a divider between reviews

Fix slot version bug and other improvements

---

ProjectLighthouse/Controllers/GameApi/Resources/PhotosController.cs

Some people were unable to upload photos due to their console being set to the wrong time. I think this is a better solution rather than rejecting the request.

Set photo timestamp to current time if timestamp is in the future

---

ProjectLighthouse.Servers.API/ProjectLighthouse.Servers.API.csproj
ProjectLighthouse.Servers.GameServer/ProjectLighthouse.Servers.GameServer.csproj
ProjectLighthouse.Servers.Website/ProjectLighthouse.Servers.Website.csproj
ProjectLighthouse/ProjectLighthouse.csproj

gets rid of the "Found multiple publish output files with the same relative path" error i encountered while publishing from dotnet cli

workaround for NETSDK1152 error

---

ProjectLighthouse.Servers.Website/Pages/Partials/SlotCardPartial.cshtml
ProjectLighthouse.Servers.Website/Pages/SlotPage.cshtml
ProjectLighthouse/PlayerData/Profiles/User.cs
ProjectLighthouse/StaticFiles/css/styles.css

This PR most notably fixes text overflowing from their containers on the front page, slot list, and the slot page itself. It also fixes HTML entities not being decoded in slot titles like `&gt;`. Closes #322.
This method does have some drawbacks like whole words sometimes being cut into two parts but otherwise, a single long word will not get wrapped.
Before
After

Fix text wrap and slot titles

---

ProjectLighthouse.Localization/LocalizationManager.cs
ProjectLighthouse.Servers.Website/Startup/WebsiteStartup.cs

This allows browsers requesting over en-GB to still get the English version before another one.
Closes #384

Update default language to be en instead of en-US

---

ProjectLighthouse.Servers.Website/Controllers/Admin/AdminReportController.cs

This kind of closes #353, I think it may also be a good idea to rename the remove all assets button because it insinuates that it will delete (unpublish) the level that the report was generated in.

Prevent grief report deletion from removing slot rootLevel

---

ProjectLighthouse.Servers.Website/Pages/Partials/CommentsPartial.cshtml

The last time I touched comments I accidentally made the comment ratings invisible 
This PR disables pointer events for the voting buttons instead of simply hiding them.

Fix posters' comments not showing ratings

---

ProjectLighthouse/Levels/Slot.cs

These are necessary to hint to the game that the level has photos instead of the game having to manually check the /photos endpoint. This was also supposed to be in the original dev slots PR but I forgot about it.

Include number of photos in slot serialization

---

ProjectLighthouse.Servers.API/Controllers/UserEndpoints.cs
ProjectLighthouse.Servers.GameServer/Controllers/Slots/PublishController.cs
ProjectLighthouse.Servers.GameServer/Middlewares/DigestMiddleware.cs
ProjectLighthouse.Servers.GameServer/Middlewares/SetLastContactMiddleware.cs
ProjectLighthouse.Servers.GameServer/Startup/GameServerStartup.cs
ProjectLighthouse.Servers.Website/Pages/SendVerificationEmailPage.cshtml
ProjectLighthouse.Servers.Website/Pages/SendVerificationEmailPage.cshtml.cs
ProjectLighthouse.Servers.Website/Startup/WebsiteStartup.cs
ProjectLighthouse/Configuration/ConfigurationCategories/AuthenticationConfiguration.cs
ProjectLighthouse/Configuration/ConfigurationCategories/RateLimitConfiguration.cs
ProjectLighthouse/Configuration/RateLimitOptions.cs
ProjectLighthouse/Configuration/RateLimitOverride.cs
ProjectLighthouse/Configuration/ServerConfiguration.cs
ProjectLighthouse/Files/FileHelper.cs
ProjectLighthouse/Logging/LogArea.cs
ProjectLighthouse/Middlewares/RateLimitMiddleware.cs
ProjectLighthouse/ProjectLighthouse.csproj

This pull request adds rate limiting to the website and game server. The API server was intentionally left out since there aren't really any public-facing POST endpoints. These rate limit options can be configured to have custom parameters for specific URLs or more generalized URLs with the use of wildcards (*). The GameServerStartup class has also been refactored to move the digest header check and the last contact update to separate middleware classes.
* Fixes a bug in LBP3 where if you republish a level from an earlier game the client tries to forcefully update the level to LBP3.
* Made the verification email log not send more than 1 email every 30 seconds.
* Reverted the change that made the verification email page reuse tokens. It will now regenerate the token and delete any existing …

Implement POST request rate limiting

---

ProjectLighthouse.Servers.Website/Pages/Partials/TwoFactorPartial.cshtml
ProjectLighthouse/StaticFiles/css/styles.css

Makes the input show a keypad instead of a normal keyboard cause you only enter numbers. 
Fixes a padding issue where some devices would add a lot of extra padding to the input boxes and make the numbers unreadable.

Fix Two-Factor form on mobile

---

.config/dotnet-tools.json
Dockerfile
ProjectLighthouse.Servers.Website/Controllers/Moderator/ModerationCaseController.cs
ProjectLighthouse.Servers.Website/Pages/Moderation/NewCasePage.cshtml.cs
ProjectLighthouse.Servers.Website/Pages/Partials/ModerationCasePartial.cshtml
ProjectLighthouse/Administration/CaseType.cs
ProjectLighthouse/Administration/ModerationCase.cs
ProjectLighthouse/Database.cs
ProjectLighthouse/Helpers/LocalizationHelper.cs
ProjectLighthouse/Helpers/SlotHelper.cs
ProjectLighthouse/Levels/Categories/HighestRatedCategory.cs
ProjectLighthouse/Levels/Categories/MostHeartedCategory.cs
ProjectLighthouse/Levels/Categories/MostPlayedCategory.cs
ProjectLighthouse/Migrations/20230127021453_AddUsernameToCaseTable.cs
ProjectLighthouse/ProjectLighthouse/Migrations/DatabaseModelSnapshot.cs

This bug was due to the fact that the case system is designed around requiring the case creator/case dismisser to exist. When you would try to delete a user that occupied either of these fields it would result in an error. This fix is definitely not the optimal solution since it uses the placeholder user but I don't have time to rewrite the entire case system. The new functionality is that when you delete a user who dismissed/created a case it will still show their username but it won't be a clickable link.
Closes #643

Fix bug where users can't be deleted

---

ProjectLighthouse/ProjectLighthouse.csproj
ProjectLighthouse/StartupTasks.cs
docker-compose.yml

This PR removes the hard dependency on the game server for migrations. Currently, if you run in Release mode, migrations will only be run if the server type is GameServer. The new functionality is that any server can run a migration, and access is controlled by a distributed lock that lives in the SQL server.  This prevents two servers from attempting to perform a migration simultaneously, which would leave the database in a potentially broken state.
Also changes docker-compose to store the asp.net data protection keys outside of the container.

Make DB migrations use a distributed lock

---

LICENSE
ProjectLighthouse.Servers.Website/Pages/Partials/ReviewPartial.cshtml

Visual changes to add link to reviewer's profile in review card, as well as wrapping the labels in a `div` and padding them for organization.

Link to reviewer in card and pad labels

---

ProjectLighthouse.Servers.Website/Pages/Partials/Links/UserLinkPartial.cshtml

This change adds global highlighting of moderator and administrator username links. Moderator users are highlighted orange [`rgb(200, 130, 0)`] and administrator users are highlighted red [`rgb(255, 0, 0)`]. Any links that utilize `ProjectLighthouse.Servers.Website/Pages/Partials/Links/UserLinkPartial.cshtml` will have this highlighting.

Highlight moderator/administrator user account links

---

ProjectLighthouse/Configuration/ConfigurationBase.cs

Now you can use environment variables in string variables for any config. The format is similar to windows because of how C# implements it. If you had a variable named `DB_ADDRESS` you would access it with `%DB_ADDRESS%`. I'm contemplating changing the default config values to include environment variables for easy setup on docker but I think that's outside the scope of this PR.

Allow environment variable expansion in config files

---

ProjectLighthouse.Servers.GameServer/Controllers/Slots/SlotsController.cs
ProjectLighthouse.Servers.GameServer/Controllers/StatisticsController.cs
ProjectLighthouse.Servers.GameServer/Types/Categories/CategoryWithUser.cs
ProjectLighthouse.Servers.GameServer/Types/Categories/CustomCategory.cs
ProjectLighthouse.Servers.GameServer/Types/Categories/HeartedCategory.cs
ProjectLighthouse.Servers.GameServer/Types/Categories/LuckyDipCategory.cs
ProjectLighthouse.Servers.GameServer/Types/Categories/MostPlayedCategory.cs
ProjectLighthouse.Servers.GameServer/Types/Categories/NewestLevelsCategory.cs
ProjectLighthouse.Servers.GameServer/Types/Categories/QueueCategory.cs
ProjectLighthouse.Servers.GameServer/Types/Categories/TeamPicksCategory.cs
ProjectLighthouse/Helpers/StatisticsHelper.cs
ProjectLighthouse/Types/Entities/Level/Slot.cs

Hello! It's been a while since my last PR, I've been working on these fixes for a while as I was to lazy up until recently to actually fix these issues. The entire changelog is listed below!
- Total players online now show the exact amount of users playing said game, lets say there's 25 people online total, there's 5 playing LBP1, 10 playing LBP2, 5 playing Vita, and 5 playing LBP3. The game show you the amount of players playing the game you're currently on. So for LBP1 it'll show 5 total players online and so on!
- Team Picks total count now show the correct amount of levels that are able to be played on said game. I did a similar update to the total level count a while back as a test and seems to be working great! This update is similar, but it only affects the Team Pick total slot …

StasticsHelper + Community Tab Performance Fix

---

ProjectLighthouse.Servers.API/Controllers/StatusController.cs
ProjectLighthouse.Servers.GameServer/Controllers/StatusController.cs
ProjectLighthouse.Servers.Website/Controllers/StatusController.cs

Currently trying to send an HTTP HEAD request to any of the status endpoints you get a 405 Method not allowed. Some automated status checks use this method because it's lightweight and doesn't return a body and may interpret the 405 response as an error.

Allow head requests to status endpoints

---

ProjectLighthouse.Servers.Website/Pages/Partials/CommentsPartial.cshtml
ProjectLighthouse.Servers.Website/Pages/UserPage.cshtml

Add input validation to the HTML form to limit comment length to 100 characters, as well as a very minor visual nitpick embedded within.

Add comment form max char limit validation

---

ProjectLighthouse.Servers.GameServer/Controllers/FriendsController.cs
ProjectLighthouse.Servers.GameServer/Controllers/ReportController.cs
ProjectLighthouse.Servers.GameServer/Controllers/Resources/PhotosController.cs
ProjectLighthouse.Servers.GameServer/Controllers/Slots/ScoreController.cs
ProjectLighthouse.Servers.GameServer/Controllers/UserController.cs
ProjectLighthouse.Servers.Website/Controllers/SlotPageController.cs
ProjectLighthouse.Servers.Website/Controllers/UserPageController.cs
ProjectLighthouse.Servers.Website/Pages/SlotSettingsPage.cshtml.cs
ProjectLighthouse.Servers.Website/Pages/UserSettingsPage.cshtml.cs
ProjectLighthouse/Administration/Maintenance/MigrationTasks/CleanupSanitizedStrings.cs
ProjectLighthouse/Extensions/ControllerExtensions.cs
ProjectLighthouse/Helpers/SanitizationHelper.cs

After the recent serialization refactor, sanitization and desensitization are both handled by the built-in .NET systems. Before, only sanitization was handled and the manual string serialization would result in potential XML injection. Since this issue is no longer present the manually sanitized strings can be manually decoded.

Fix doubly sanitized strings

---

ProjectLighthouse.Servers.GameServer/Controllers/Slots/ScoreController.cs
ProjectLighthouse/Types/Serialization/MultiScoreboardResponse.cs

Implements missing endpoints in LBP1 to show highest scores and friend scores.
This also seems to have been the reason that comments in lbp1 were so buggy. After implementing the scoreboard endpoint comments loaded instantly and the next and previous page behaved correctly.
Closes #411 and closes #470
<details>
<summary>Pictures</summary>
</details>

Add LBP1 level scoreboards

---

ProjectLighthouse.Servers.API/Controllers/SlotEndpoints.cs
ProjectLighthouse.Servers.API/Controllers/UserEndpoints.cs
ProjectLighthouse.Servers.GameServer/Controllers/CommentController.cs
ProjectLighthouse.Servers.GameServer/Controllers/Resources/PhotosController.cs
ProjectLighthouse.Servers.GameServer/Controllers/Slots/CollectionController.cs
ProjectLighthouse.Servers.GameServer/Controllers/Slots/ListController.cs
ProjectLighthouse.Servers.GameServer/Controllers/Slots/ReviewController.cs
ProjectLighthouse.Servers.GameServer/Controllers/Slots/ScoreController.cs
ProjectLighthouse.Servers.GameServer/Controllers/Slots/SearchController.cs
ProjectLighthouse.Servers.GameServer/Controllers/Slots/SlotsController.cs
ProjectLighthouse/Extensions/ControllerExtensions.cs
ProjectLighthouse/Extensions/QueryExtensions.cs
ProjectLighthouse/Serialization/CustomXmlSerializer.cs
ProjectLighthouse/Serialization/LighthouseSerializer.cs
ProjectLighthouse/Types/Levels/Category.cs
ProjectLighthouse/Types/Serialization/GamePhoto.cs

Currently, there is a memory leak issue in the lighthouse GameServer. I believe it is caused by the allocation of ILbpSerializable objects before the final aggregation in LINQ. For example, to get a list of slots the current way is done like so:
```csharp
await this.database.Slots.Where(s => s.TeamPick).Take(30).Select(s => SlotBase.CreateFromEntity(s)).ToListAsync()
//                                                  ^ this is the problem
```
This results in SlotEntity not being garbage collected because somehow a reference is still held
My proposed fix is first to aggregate the SlotEntity query into a list and then call Select() and ToList(), which would look something like this:
```csharp
(await this.database.Slots.Where(s => s.TeamPick).Take(30).ToListAsync()).Select(s => …
```

Fix memory leak in GameServer

---

ProjectLighthouse.Servers.GameServer/Controllers/Slots/SlotsController.cs
ProjectLighthouse.Servers.GameServer/Types/Categories/HighestRatedCategory.cs
ProjectLighthouse.Servers.GameServer/Types/Categories/MostHeartedCategory.cs
ProjectLighthouse/Types/Misc/SlotMetadata.cs
ProjectLighthouse/Types/Serialization/GameUserSlot.cs

Removes usages of client-side evaluation which should help to improve performance in endpoints that are sorted by calculated fields (most hearted, highest rated, etc)
Also removes the serialization of a slot's resources since it isn't used by the game at all.

Optimize slot endpoints

---

ProjectLighthouse.Servers.Website/Controllers/Moderator/ModerationSlotController.cs
ProjectLighthouse.Servers.Website/Pages/Partials/SlotCardPartial.cshtml

This PR adds the basic ability for users to flag duplicated levels on the instance. Upon clicking the red button and confirming, a webhook is delivered to the configured `WebhookDestination.Moderation` URL, containing the duplicate level name/ID, as well as the reporter/level creator usernames. This allows whoever is reviewing the case to verify the original uploader as opposed to the copied level.

Add basic ability to flag duplicate levels

---

ProjectLighthouse.Servers.Website/Pages/Login/BannedUserPage.cshtml
ProjectLighthouse.Servers.Website/Pages/Login/BannedUserPage.cshtml.cs

Patches two issues arising from #773.
* Two title headings would display on page
* Renderer would pull oldest case rather than newest, and would still show dismissed cases.
* Technically, showing a dismissed case shouldn't happen anyways, but still a good thing to check for.

Patch account suspended page display issues

---

ProjectLighthouse.Tests.WebsiteTests/ProjectLighthouse.Tests.WebsiteTests.csproj

Manually bumping Selenium.WebDriver to 4.10.0 because Dependabot was having some issues with status checks.

Bump Selenium.WebDriver from 4.9.1 to 4.10.0

---

ProjectLighthouse.Servers.Website/Pages/Email/SetEmailForm.cshtml
ProjectLighthouse.Servers.Website/Pages/Login/LoginForm.cshtml
ProjectLighthouse.Servers.Website/Pages/Login/PasswordResetPage.cshtml
ProjectLighthouse.Servers.Website/Pages/Login/PasswordResetRequestForm.cshtml
ProjectLighthouse.Servers.Website/Pages/Login/RegisterForm.cshtml
ProjectLighthouse.Servers.Website/Pages/Moderation/NewCasePage.cshtml
ProjectLighthouse.Servers.Website/Pages/Partials/ErrorModalPartial.cshtml
ProjectLighthouse.Servers.Website/Pages/Partials/TwoFactorPartial.cshtml

As suggested in https://github.com/LBPUnion/ProjectLighthouse/pull/781#discussion_r1218575630, this PR refactors the commonly used error modal into it's own partial to prevent duplicate code.
Recommended usage for this modal:
```cs
@if (!string.IsNullOrWhiteSpace(Model.Error))
{
@await Html.PartialAsync("Partials/ErrorModalPartial", (Model.Translate(GeneralStrings.Error), Model.Error), ViewData)
}
```

Refactor error modal into its own partial

---

ProjectLighthouse.Servers.API/Controllers/UserEndpoints.cs

This PR adds an endpoint which lists all currently online users by their login time. This could be useful for services that want to deal with all currently online users at once but don't want to use some other inefficient method of obtaining the users.

Add online users endpoint to user API

---

ProjectLighthouse.Localization/General.resx
ProjectLighthouse.Localization/StringLists/GeneralStrings.cs
ProjectLighthouse.Servers.GameServer/Controllers/MessageController.cs
ProjectLighthouse.Servers.Website/Pages/AnnouncePage.cshtml
ProjectLighthouse.Servers.Website/Pages/AnnouncePage.cshtml.cs
ProjectLighthouse.Servers.Website/Pages/Layouts/BaseLayout.cshtml.cs
ProjectLighthouse.Tests.GameApiTests/Unit/Controllers/MessageControllerTests.cs
ProjectLighthouse.Tests.WebsiteTests/Integration/AdminTests.cs
ProjectLighthouse/Database/DatabaseContext.cs
ProjectLighthouse/Migrations/20230620211613_AddWebAnnouncementsToDb.cs
ProjectLighthouse/ProjectLighthouse/Migrations/DatabaseModelSnapshot.cs
ProjectLighthouse/Types/Entities/Website/WebsiteAnnouncementEntity.cs

This PR changes a few things pertaining to announcements.
* Implements a web-based announcements system
* Optimizes /announce to use a StringBuilder
First off, I improved the /announce game server endpoint in 144e952bde2bf80d0e8fb52212ec4c288091fa8b to use a string builder instead of re-assigning string modifications over and over again.
Second, I implemented a website-based announcements system in 4f89c10f1ccceb325a7dcc978c6ac41385ed3f37 which will allow instance administrators to send out announcements to users. I opted to condense the changes across several commits into one singular commit to improve organization.
Last, I added Discord webhook support in d5b773926eb9ff645bc39ca749e74dfb8d8c0bba which sends new announcements to the configured Discord webhook, if set up. …

Optimize GameServer /announce and add website announcements

---

ProjectLighthouse.Servers.GameServer/Controllers/CommentController.cs
ProjectLighthouse.Servers.Website/Controllers/Moderator/ModerationPageController.cs
ProjectLighthouse.Servers.Website/Pages/Moderation/ModPanelPage.cshtml
ProjectLighthouse.Servers.Website/Pages/SlotPage.cshtml.cs
ProjectLighthouse/Types/Serialization/GameComment.cs

The primary reason for this PR is currently it isn't really possible for mods to delete abusive comments or scores on story levels.
This PR adds an extra comment on story levels that shows the story levels ID and slot ID. This comment only displays to moderators and will always be at the top of the comments. This is so that mods can easily find the story level id that a bad score/comment is on.
The mod panel on the website has a new form that lets people easily put in a story level ID and be redirected to the slot page.
Then finally, mods are now able to directly access story levels on the website, it looks something like this:

Allow moderators to moderate story levels

---

ProjectLighthouse.Localization/Moderation.resx
ProjectLighthouse.Servers.Website/Pages/Login/BannedUserPage.cshtml
ProjectLighthouse.Servers.Website/Pages/Login/BannedUserPage.cshtml.cs

This PR fixes the issue where the ban information page would improperly pull the user's latest moderation case, pulling the latest dismissed case rather than the latest case where expiration isn't null (which should theoretically never happen anyways, but should still check since it is marked as nullable in the database).
Also properly implements the existing permanent ban string into the information page, as well as fixes a missing page element when the case is null.

Fix null case bug in BannedUserPage and properly add no expiration text

---

ProjectLighthouse.Servers.GameServer/Controllers/Slots/PublishController.cs
ProjectLighthouse.Servers.Website/Pages/SlotPage.cshtml
ProjectLighthouse.Servers.Website/Pages/UserPage.cshtml
ProjectLighthouse/Administration/Maintenance/RepeatingTasks/PerformCaseActionsTask.cs
ProjectLighthouse/Migrations/20230707125059_AddModerationLevelLocks.cs
ProjectLighthouse/ProjectLighthouse/Migrations/DatabaseModelSnapshot.cs
ProjectLighthouse/Types/Entities/Level/SlotEntity.cs
ProjectLighthouse/Types/Moderation/Cases/CaseType.cs

This PR adds a new mod case type which allows moderators to forcibly lock levels. Forcibly locking a level sets the level's InitiallyLocked variable, as well as the reason for the lock. It also sets the LockedByModerator variable, which is checked upon re-publish to make sure the user cannot just unlock the level.
<details>
<summary>Images</summary>
<br>
</details>

Add the ability for moderators to forcibly lock levels

---

ProjectLighthouse.Servers.Website/Pages/Partials/ReportPartial.cshtml

Pretty self explanatory - since the grief report only contains the username of the user instead of the ID, I made the clickable links redirect to the search page for that username.

Add workaround for the clickable user links in a grief report

---

ProjectLighthouse.Localization/Profile.resx
ProjectLighthouse.Localization/StringLists/ProfileStrings.cs
ProjectLighthouse.Servers.Website/Extensions/FormattingExtensions.cs
ProjectLighthouse.Servers.Website/Pages/Partials/UserCardPartial.cshtml
ProjectLighthouse.Servers.Website/Pages/UserSettingsPage.cshtml
ProjectLighthouse.Servers.Website/Pages/UserSettingsPage.cshtml.cs
ProjectLighthouse/Migrations/20230827004014_AddProfileVanityTagsToUsers.cs
ProjectLighthouse/ProjectLighthouse/Migrations/DatabaseModelSnapshot.cs
ProjectLighthouse/StaticFiles/css/styles.css
ProjectLighthouse/Types/Entities/Profile/UserEntity.cs

This PR simplifies the website rank badges to use existing classes, and also implements a small feature that allows server administrators to grant vanity profile tags to users, i.e. for winning an event.

Simplify rank badges and implement profile tags

---

ProjectLighthouse.Servers.Website/Controllers/Admin/AdminUserController.cs
ProjectLighthouse.Servers.Website/Controllers/Moderator/ModerationCaseController.cs
ProjectLighthouse.Servers.Website/Pages/Admin/AdminPanelPage.cshtml.cs
ProjectLighthouse.Servers.Website/Pages/Admin/AdminPanelUsersPage.cshtml
ProjectLighthouse.Servers.Website/Pages/Admin/AdminPanelUsersPage.cshtml.cs
ProjectLighthouse.Servers.Website/Pages/Moderation/CasePage.cshtml
ProjectLighthouse.Servers.Website/Pages/Moderation/CasePage.cshtml.cs
ProjectLighthouse.Servers.Website/Pages/Partials/ModerationCasePartial.cshtml
ProjectLighthouse/Administration/Maintenance/RepeatingTasks/DismissExpiredCasesTask.cs

This PR adds a few quality of life features and fixes to the moderation case page and case partial.
* Adds pagination to the moderation case page to reduce database strain for instances with large amounts of cases
* Fully implements the search functionality of the moderation case page
* Extends and simplifies the case status indicators, basically a tail end to #891
* Disable the ability to dismiss cases "early" after they've been expired to allow for a seamless process of dismissal
* Turned down the repeat time of the dismissal task to every 1 hour
Technically outside the scope of this PR, but also throws in pagination and search functionality into the admin users list.

Improve moderation case page and case partial

---

ProjectLighthouse.Servers.API/Controllers/UserEndpoints.cs
ProjectLighthouse/Database/DatabaseContext.ApiTokens.cs

This should allow for easier authentication of API calls in the future when it becomes needed.

Move API authentication logic into DatabaseContext partial class

---

ProjectLighthouse.Servers.Website/Pages/Layouts/BaseLayout.cshtml
ProjectLighthouse/Helpers/VersionHelper.cs

Adds hyperlinks to the upstream LICENSE file, as well as the active git remote, to help better comply with AGPL's requirements.

Add links to license and source code in footer

---

ProjectLighthouse.Servers.GameServer/Controllers/Resources/PhotosController.cs
ProjectLighthouse.Servers.GameServer/Controllers/Resources/ResourcesController.cs
ProjectLighthouse.Servers.GameServer/Controllers/UserController.cs
ProjectLighthouse.Servers.Website/Controllers/Admin/AdminUserController.cs
ProjectLighthouse.Tests/Unit/ResourceTests.cs
ProjectLighthouse/Files/FileHelper.cs
ProjectLighthouse/Types/Resources/LbpFile.cs

Pretty self-explanable. This PR prevents people from trying to put payloads in resource hashes like path traversals or HTML escapes. I don't think this needs an entire migration, it should be relatively simple for server owners to fix any occurrences of invalid resources and I don't think the issue is that widespread at the moment.

Add checks for resource strings

---

ProjectLighthouse.Servers.GameServer/Startup/GameServerStartup.cs

This PR changes the message that shows when the digestKey has not been set to better reflect what will/won't work if left unset.

Missing digest message change

---

ProjectLighthouse.Servers.Website/Extensions/SlugExtensions.cs
ProjectLighthouse.Servers.Website/Pages/Partials/Links/UserLinkPartial.cshtml
ProjectLighthouse.Servers.Website/Pages/Partials/SlotCardPartial.cshtml
ProjectLighthouse.Servers.Website/Pages/Partials/UserCardPartial.cshtml
ProjectLighthouse.Servers.Website/Pages/SlotPage.cshtml
ProjectLighthouse.Servers.Website/Pages/SlotPage.cshtml.cs
ProjectLighthouse.Servers.Website/Pages/UserPage.cshtml
ProjectLighthouse.Servers.Website/Pages/UserPage.cshtml.cs

Slugs are generated by stripping out all characters that aren't alphanumeric (a-Z, 0-9, and spaces) and replacing spaces with dashes then finally transforming everything into lowercase so "3-D platformer level" gets turned into "3d-platformer-level"
and "<UPDATED 3/7/70> Test & Buy" gets turned into "updated-3770-test-buy"
Closes #146

Implement URL slugs 

---

ProjectLighthouse.Servers.GameServer/Controllers/MessageController.cs
ProjectLighthouse.Servers.Website/Pages/SlotPage.cshtml.cs
ProjectLighthouse.Servers.Website/Pages/UserPage.cshtml.cs
ProjectLighthouse/Administration/Maintenance/RepeatingTasks/DismissExpiredCasesTask.cs

This PR addresses a few minor issues and fixes a few things.
* Sub-levels would be displayed on a user's profile when logged out
* Fixes an issue when trying to directly access a sub-level page on the website as the slot creator
* Mark automatically dismissed cases as unprocessed so the repeating task will perform case actions
* Use a foreach for notifications
* It was thought that modifying a collection item while iterating over the list would throw an exception but this is exactly what the automatic case dismissal repeating task does. Tested this and it works perfectly fine.

Miscellaneous website/moderation/notification fixes

---

ProjectLighthouse.Servers.Website/Pages/SlotPage.cshtml

Self-explanatory PR. Adds a box above the level tags with the rootlevel hash, displayed to mods and admins. Also removes whitespace in the modified file (Rider automated)

Show rootlevel hash to moderators on slot page

---

ProjectLighthouse.Tests.GameApiTests/Unit/Controllers/CommentControllerTests.cs
ProjectLighthouse.Tests.GameApiTests/Unit/Controllers/MessageControllerTests.cs
ProjectLighthouse.Tests.GameApiTests/Unit/Controllers/SlotControllerTests.cs
ProjectLighthouse.Tests.GameApiTests/Unit/Controllers/StatisticsControllerTests.cs
ProjectLighthouse.Tests.GameApiTests/Unit/Middlewares/DigestMiddlewareTests.cs
ProjectLighthouse.Tests.GameApiTests/Unit/Middlewares/SetLastContactMiddlewareTests.cs
ProjectLighthouse.Tests/Helpers/MockHelper.cs
ProjectLighthouse.Tests/ProjectLighthouse.Tests.csproj
ProjectLighthouse.Tests/Unit/ModerationTests.cs

Currently, we use the InMemory EF provider which has some issues like not enforcing referential integrity (a level can exist without a creator). It also doesn't detect potential issues with database schema. Switching to in-memory SQLite fixes both these issues and will make unit tests more realistic.

Migrate to SQLite EF provider for testing

---

ProjectLighthouse.Servers.API/Controllers/UserEndpoints.cs
ProjectLighthouse.Servers.Website/Controllers/Moderator/ModerationCaseController.cs
ProjectLighthouse.Servers.Website/Pages/Email/CompleteEmailVerificationPage.cshtml.cs
ProjectLighthouse.Servers.Website/Pages/Login/LoginForm.cshtml.cs
ProjectLighthouse.Servers.Website/Pages/Login/RegisterForm.cshtml.cs
ProjectLighthouse.Servers.Website/Pages/Moderation/NewCasePage.cshtml.cs
ProjectLighthouse.Tests.WebsiteTests/Integration/AdminTests.cs
ProjectLighthouse.Tests.WebsiteTests/Integration/AuthenticationTests.cs
ProjectLighthouse/Administration/Maintenance/Commands/CreateAPIKeyCommand.cs
ProjectLighthouse/Administration/Maintenance/MaintenanceHelper.cs
ProjectLighthouse/Database/DatabaseContext.GameTokens.cs
ProjectLighthouse/Database/DatabaseContext.Utils.cs
ProjectLighthouse/Database/DatabaseContext.WebTokens.cs
ProjectLighthouse/Helpers/EmailHelper.cs
ProjectLighthouse/Types/Entities/Moderation/ModerationCaseEntity.cs

`DateTime.Now` uses local machine time which would potentially cause discrepancies with timekeeping for token or case expirations.

Use UtcNow instead of Now for internal time keeping

---

ProjectLighthouse/Migrations/DatabaseContextModelSnapshot.cs

Removes the dreaded `ProjectLighthouse\ProjectLighthouse\Migrations` folder. This should have also been renamed when we renamed the `Database` class to `DatabaseContext` since the format of the class is `<YourContext>ModelSnapshot.cs`

Rename the database model snapshot and move it to the actual migrations folder

---

ProjectLighthouse/Database/DatabaseContext.WebTokens.cs
ProjectLighthouse/Helpers/EmailHelper.cs

This PR adds an expiration for password reset tokens (they used to live forever apparently) and also prevents someone from generating a new password reset request unless the old one has been removed either manually or after the automated 24h period.

Prevent password reset spam

---

ProjectLighthouse.Servers.API/Responses/ApiSlot.cs
ProjectLighthouse.Servers.API/Responses/MinimalApiSlot.cs
ProjectLighthouse.Servers.GameServer/Controllers/Slots/SlotsController.cs
ProjectLighthouse.Servers.GameServer/Types/Categories/TeamPicksCategory.cs
ProjectLighthouse.Servers.Website/Controllers/Moderator/ModerationSlotController.cs
ProjectLighthouse.Servers.Website/Pages/LandingPage.cshtml.cs
ProjectLighthouse.Servers.Website/Pages/SlotPage.cshtml
ProjectLighthouse.Tests.GameApiTests/Unit/Controllers/SlotControllerTests.cs
ProjectLighthouse.Tests.GameApiTests/Unit/Controllers/StatisticsControllerTests.cs
ProjectLighthouse.Tests/Unit/FilterTests.cs
ProjectLighthouse/Filter/Filters/TeamPickFilter.cs
ProjectLighthouse/Filter/Sorts/TeamPickSort.cs
ProjectLighthouse/Migrations/20240214031744_UpdateTeamPickBoolToTimestamp.cs
ProjectLighthouse/Migrations/DatabaseContextModelSnapshot.cs
ProjectLighthouse/Types/Entities/Level/SlotEntity.cs
ProjectLighthouse/Types/Serialization/SlotBase.cs

Instead of sorting team picks by the time the level was last updated or uploaded, we can store when the level was picked and sort by that instead. On migration, already team-picked levels are set to a timestamp of 1 so they will still count as team-picked but will all show up last.

Sort team picks by the time they were team picked

---

ProjectLighthouse.Localization/BaseLayout.resx
ProjectLighthouse.Localization/StringLists/BaseLayoutStrings.cs
ProjectLighthouse.Servers.GameServer/Controllers/CommentController.cs
ProjectLighthouse.Servers.GameServer/Controllers/MessageController.cs
ProjectLighthouse.Servers.GameServer/Controllers/Resources/PhotosController.cs
ProjectLighthouse.Servers.GameServer/Controllers/Resources/ResourcesController.cs
ProjectLighthouse.Servers.GameServer/Controllers/Slots/PublishController.cs
ProjectLighthouse.Servers.GameServer/Controllers/Slots/ReviewController.cs
ProjectLighthouse.Servers.GameServer/Controllers/UserController.cs
ProjectLighthouse.Servers.Website/Controllers/SlotPageController.cs
ProjectLighthouse.Servers.Website/Controllers/UserPageController.cs
ProjectLighthouse.Servers.Website/Pages/LandingPage.cshtml
ProjectLighthouse.Servers.Website/Pages/LandingPage.cshtml.cs
ProjectLighthouse.Servers.Website/Pages/Layouts/BaseLayout.cshtml
ProjectLighthouse.Servers.Website/Pages/Partials/CommentsPartial.cshtml
ProjectLighthouse.Servers.Website/Pages/Partials/ReviewPartial.cshtml
ProjectLighthouse.Servers.Website/Pages/SlotSettingsPage.cshtml.cs
ProjectLighthouse.Servers.Website/Pages/UserSettingsPage.cshtml.cs
ProjectLighthouse/Configuration/ConfigurationCategories/UserGeneratedContentLimitConfiguration.cs
ProjectLighthouse/Configuration/ServerConfiguration.cs

This PR implements the ability to put an instance in a "read-only" state.
The following actions are limited or disabled while in read-only mode:
* Level uploads or changes
* Photo uploads
* General asset uploads (/upload/hash)
* Profile picture/biography changes
* Post/delete comments
* Post/delete reviews
A message will also be appended to the base website layout, as well as the /announce endpoint.
This could probably be refactored into a simple middleware or something in the future.

Implement read-only mode

---

.github/workflows/docker-publish.yml

Use Actions to build and publish Docker images to Github Container Registry

---

ProjectLighthouse.Servers.GameServer/Controllers/Slots/ReviewController.cs
ProjectLighthouse.Tests.GameApiTests/Unit/Controllers/ReviewControllerTests.cs

There is currently a bug where if you review an LBP3 level and load your profile in LBP2 the game freaks out because the level data won't be returned because of the GameVersionFilter. This PR adds similar filtering so that reviews from higher game versions are no longer returned. This change adds an extra SQL join to the review query.
new example generated query:
```sql
.param set @__targetUserId_0 1
.param set @__token_GameVersion_1 1
SELECT "r"."ReviewId", "r"."Deleted", "r"."DeletedBy", "r"."LabelCollection", "r"."ReviewerId", "r"."SlotId", "r"."Text", "r"."Thumb", "r"."ThumbsDown", "r"."ThumbsUp", "r"."Timestamp"
FROM "Reviews" AS "r"
INNER JOIN "Slots" AS "s" ON "r"."SlotId" = "s"."SlotId"
WHERE "r"."ReviewerId" = @__targetUserId_0 AND "s"."GameVersion" <= @__token_GameVersion_1 …
```

Prevent LBP3 reviews from showing up in LBP2

---

ProjectLighthouse.Servers.Website/Controllers/Admin/AdminUserController.cs
ProjectLighthouse.Servers.Website/Pages/UserPage.cshtml

Implement the ability to forcibly verify a user's email

---

ProjectLighthouse.Servers.Website/Controllers/Admin/AdminUserController.cs
ProjectLighthouse.Servers.Website/Pages/UserPage.cshtml

Title is fairly self-explanatory.
This PR allows moderators/admins to delete every score or comment posted by a user from the user page.
These features were requested by a Beacon moderator after some recent comment and hacked score spam.

Implement the ability for moderators to delete all scores/comments by a user

---

ProjectLighthouse.Servers.Website/Pages/Debug/VersionInfoPage.cshtml
ProjectLighthouse.Servers.Website/Pages/Layouts/BaseLayout.cshtml
ProjectLighthouse/Helpers/VersionHelper.cs
ProjectLighthouse/StartupTasks.cs

Closes #1032.
---
It's quite annoying and doesn't really do anything, it can also trigger on people who didn't modify the source code.
It is also very easy to disable it by making a commit in the local repo or just by changing `IsDirty` to always return `true`

Remove license check

---

ProjectLighthouse.Tests.GameApiTests/Integration/DatabaseTests.cs
ProjectLighthouse/Helpers/CryptoHelper.cs
ProjectLighthouse/Helpers/EmailHelper.cs

Base64 encode auth tokens to make them more URL compatible, i.e when they are used in emails.
Fixes #1023

Base64 encode auth tokens

---

ProjectLighthouse.Servers.GameServer/Controllers/Slots/SlotsController.cs
ProjectLighthouse.Servers.GameServer/Extensions/ControllerExtensions.cs
ProjectLighthouse.Servers.GameServer/Types/Categories/LuckyDipCategory.cs
ProjectLighthouse/Filter/Filters/LockedSlotFilter.cs

filters locked levels out of lucky dip
iirc this was the functionality on official servers, and makes sense anyway

filter locked levels from lucky dip

---

ProjectLighthouse.Servers.API/Controllers/StatisticsEndpoints.cs
ProjectLighthouse.Servers.API/Responses/PlayerCountResponse.cs
ProjectLighthouse.Servers.API/Responses/PlayerListResponse.cs
ProjectLighthouse.Servers.GameServer/Controllers/StatisticsController.cs
ProjectLighthouse/Helpers/StatisticsHelper.cs

This PR adds new endpoints to the v1 API to support fetching player counts grouped by platform as well as fetching the entire list of online users.
Example `/api/v1/players` response:
```json
{
"players": [
{
"username": "Slendy",
"game": "LittleBigPlanet2",
"platform": "RPCS3"
}
]
}
```
Example `/api/v1/playerCount/platform` response:
```json
{
"platforms": [
{
"platform": "PS3",
"playerCount": 0
},
{
"platform": "RPCS3",
"playerCount": 1
},
{
"platform": "Vita",
"playerCount": 0
},
{
"platform": "PSP",
"playerCount": 0
}
],
"totalPlayerCount": 1
}
```

Implement player count per platform and player list API endpoints

---

ProjectLighthouse.Servers.Website/Controllers/Admin/AdminUserController.cs
ProjectLighthouse.Servers.Website/Pages/UserPage.cshtml

This button will just allow moderators and admins to remove the user avatar from a profile for either moderation, or other purposes. The main reason for implementation is to work around an issue where sometimes, loading profile images from the website in-game (at least in LBP2) can create major issues with loading any other images in-game, which usually leads to a crash. My best guess is that it's some sort of memory leak.

Add button and controller to remove user avatar

---

ProjectLighthouse/Tickets/NPTicket.cs

RPCN is changing their ticket generator backend to use the same issuer ID as PSN meaning we can no longer use it to easily identify is a ticket is RPCN. Fortunately, the signature section of the ticket in RPCN is constant and we can just check that instead.

Identify NpTicket platform based on signature identifier instead of issuer ID

---

ProjectLighthouse.Localization/StringLists/TwoFactorStrings.cs
ProjectLighthouse.Localization/TwoFactor.resx
ProjectLighthouse.Servers.Website/Pages/TwoFactor/SetupTwoFactorPage.cshtml

Allows users who can't scan the QR code to add 2FA to their account. It also adds a couple of new translations for the text and the copy button.

Allow users to manually setup two factor with secret key

---

.github/workflows/qodana_code_quality.yml
ProjectLighthouse.Servers.GameServer/Controllers/Login/LoginController.cs
ProjectLighthouse/Configuration/ConfigurationCategories/AuthenticationConfiguration.cs
ProjectLighthouse/Configuration/ServerConfiguration.cs
ProjectLighthouse/Types/Users/Platform.cs

Due to a recent increate in abuse of our platform, I have implemented an option to disallow initial signup from certain platforms. It defaults to allow all signup attempts but can be easily restricted in the config. Also fixes the Qodana warnings in LoginController.cs

Add config options to restrict signup on certain platforms

---

ProjectLighthouse.Servers.Website/Controllers/Moderator/ModerationRemovalController.cs

This PR refactors the web comment deletion routine within [ModerationRemovalController.cs](https://github.com/LBPUnion/ProjectLighthouse/blob/main/ProjectLighthouse.Servers.Website/Controllers/Moderator/ModerationRemovalController.cs) by reworking how the notification text is determined, as well as adding handles for cases where the user is trying to delete comments on their own profile/level (this currently throws an exception in prod, it was never handled when notifications were implemented apparently).
Brings the cognitive complexity of the method down by about 30%, for those interested in that sort of thing.

Refactor web-based comment deletion routine

---

.idea/.idea.ProjectLighthouse/.idea/projectSettingsUpdater.xml
ProjectLighthouse.Servers.GameServer/Controllers/CommentController.cs
ProjectLighthouse.Servers.GameServer/Controllers/MessageController.cs
ProjectLighthouse.Servers.GameServer/Controllers/Slots/PublishController.cs
ProjectLighthouse.Servers.GameServer/Controllers/Slots/ReviewController.cs
ProjectLighthouse.Servers.GameServer/Controllers/UserController.cs
ProjectLighthouse.Servers.Website/Controllers/SlotPageController.cs
ProjectLighthouse.Servers.Website/Controllers/UserPageController.cs
ProjectLighthouse.Servers.Website/Pages/Debug/FilterTestPage.cshtml.cs
ProjectLighthouse.Servers.Website/Pages/SlotSettingsPage.cshtml.cs
ProjectLighthouse.Servers.Website/Pages/UserSettingsPage.cshtml.cs
ProjectLighthouse/Helpers/CensorHelper.cs
ProjectLighthouse/Types/Filter/FilterLocation.cs

This PR deals with places where filtering should happen but does not. I have also moved logging into the filter helper itself to reduce duplicate code and remove inconsistencies where some filtered items are logged and some are not.

Fix missing filtering, filter inconsistencies, and filter logging

---

.github/workflows/ci.yml

GitHub is deprecating `upload-artifact@v3` on November 30, 2024 and after that date any workflow still using v3 will fail.

Upgrade upload artifact action to v4

---

.github/workflows/ci.yml
.github/workflows/qodana_code_quality.yml

CI pipeline is failing due to `actions-setup-mysql` and the CodeQL action v2 has been deprecated

Update Github Action versions

---

.github/workflows/ci.yml
ProjectLighthouse.Servers.GameServer/Controllers/Slots/ScoreController.cs
ProjectLighthouse/Database/DatabaseContext.Notifications.cs
ProjectLighthouse/Types/Entities/Level/SlotEntity.cs
ProjectLighthouse/Types/Entities/Profile/UserEntity.cs

Notify a user when their highscore is beaten

---

.github/workflows/qodana_code_quality.yml
ProjectLighthouse/Tickets/Parser/TicketParser21.cs

This PR correctly reads the section header of the "entitlements" section within the NPTicket so it can skip the right number of bytes, as in rare cases there is extra data in this section.

Handle long entitlements section in NPTicket 2.1 tickets

---

ProjectLighthouse.Servers.GameServer/Controllers/Login/LoginController.cs
ProjectLighthouse.Servers.GameServer/Controllers/Login/LogoutController.cs
ProjectLighthouse.Servers.GameServer/Controllers/MessageController.cs
ProjectLighthouse.Servers.GameServer/Helpers/PatchworkHelper.cs
ProjectLighthouse.Servers.Website/Controllers/AutoDiscoverController.cs
ProjectLighthouse.Servers.Website/Types/AutoDiscoverResponse.cs
ProjectLighthouse.Tests.GameApiTests/Unit/PatchworkUserAgentTests.cs
ProjectLighthouse/Configuration/ConfigurationCategories/AuthenticationConfiguration.cs
ProjectLighthouse/Configuration/ConfigurationCategories/CustomizationConfiguration.cs
ProjectLighthouse/Configuration/ServerConfiguration.cs

This PR adds the refresh autodiscover endpoint to the website server, so that refresher can be used with minimal friction

Implement refresh autodiscover

---

ProjectLighthouse/Administration/Maintenance/Commands/RemoveTwoFactorCommand.cs

This PR adds a command to remove a users 2fa configuration, so that the database doesn't need to be manually edited.

Add command to remove user's 2fa configuration.
